import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <img src="/83b249a1-593f-4173-9e9d-7163b0079cf9.jpg" className='w-full' alt="" />

    </div>
  )
}
